app.version=0.1.0
app.id=net.dynart.neonsignal
app.mainclass=net.dynart.neonsignal.IOSLauncher
app.executable=NeonSignal
app.build=1
app.name=Neon Signal
ios.signingIdentity=Apple Development: Gabor Laszlo (N36B53W262)
